### PR TITLE
Added missing call to unit test main

### PR DESCRIPTION
**Pull request by Piyush13y**

### CODE REVIEW

**Comment by hunterhector** [comment]
Thanks for the PR. is the goal simply adding the `main` function? This isn't required for test classes, do you have reasons to add them?

**Comment by Piyush13y** [comment]
> Thanks for the PR. is the goal simply adding the `main` function? This isn't required for test classes, do you have reasons to add them?

It's just for consistency, since we are calling the main function in most of our test files in Forte as well. Some files were calling it and some weren't in ForteHealth.

**Comment by hunterhector** [comment]
> > Thanks for the PR. is the goal simply adding the `main` function? This isn't required for test classes, do you have reasons to add them?
> 
> It's just for consistency, since we are calling the main function in most of our test files in Forte as well. Some files were calling it and some weren't in ForteHealth.

It is fine to include them. Just for my information, where are we "calling the main functions"? For Forte tests, we are using `pytest tests`, which will find the test functions without needing to using `__main__` functions.

**Review by hunterhector — APPROVED** [review]

**Comment by hunterhector** [comment]
> We aren't really "calling" the main functions anywhere, we just have them in all our test files and it enables the functionality to run the test individually without pytest. With pytest, as you mentioned correctly, we don't even need to add it. However, it lets contributors run individual tests without pytest incase they aren't aware of it. At this point however, its mostly a cosmetic change for consistency. Do you think we should be phasing it out since its nugatory?

It is alright to have it here. Just check with you to make sure we didn't rely on these main functions in our CI.

**Pull request merged**
